# Generated by Django 4.2.2 on 2023-06-23 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileac',
            name='idContact',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, unique=True, verbose_name='contact identifier'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='This email also serves as identifier.', max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('entity_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('idDocument', models.PositiveIntegerField(verbose_name='document identifier')),
                ('provided_title', models.CharField(max_length=300, verbose_name='provided title')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount, from the considered individual perspective.So, a negative amount is a debt owned by an individuel to the club.  ', max_digits=7, verbose_name='amount')),
                ('date_event', models.DateField(verbose_name='date of the transaction')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last check')),
                ('imported_date', models.DateTimeField(auto_now_add=True, verbose_name='date of first import')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='state of deletion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
