# Generated by Django 4.2.2 on 2023-06-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_operations', '0002_alter_profileac_idcontact_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileac',
            name='current_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='initial balance'),
        ),
        migrations.AddField(
            model_name='profileac',
            name='initial_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='initial balance'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Transaction amount, from the considered individual perspective.So, a negative amount is a debt owned by an individuel to the club, or a paiement from the club.  ', max_digits=7, verbose_name='amount'),
        ),
    ]
